### PR TITLE
Be who you were born to be! :dizzy:

### PR DESCRIPTION
**Pull request by iamvery**
cc @bryanp, @mjcarroll

### CODE REVIEW

**Comment by iamvery** [comment]
I made this up. Thoughts?

**Comment by bryanp** [comment]
I like the first sentence, but the second sentence seems a bit vague to me. What does it mean to serve as a representative of a business in this context?

**Comment by iamvery** [comment]
I was trying to communicate that you don't have to _hide_ your affiliation with a company, just don't _be_ the company. Maybe that shouldn't be stated? I suppose it's not really the point...

**Comment by bryanp** [comment]
Ah, I see. I think we could do without it, but don't have a super strong opinion on it :)

**Comment by iamvery** [comment]
:+1: pulling it

**Comment by iamvery** [comment]
@mjcarroll merge if you like it

**Pull request merged**
